[mypy]
python_version = 3.12
strict = true
exclude = scripts/
    labs/.*/scripts/
    tests/

[mypy-tests.*]
ignore_errors = true

[mypy-scripts.*]
ignore_errors = true

[mypy-click.*]
ignore_missing_imports = true

[mypy-click.testing.*]
ignore_missing_imports = true
